credentials:
  system:
    domainCredentials:
    - credentials:
      - vaultAppRoleCredential:
          description: "vault-jenkins-role"
          id: "vault-jenkins-role"
          path: "approle"
          roleId: "d7d9ec5e-ff97-a4b9-535a-4a10769534ed"
          scope: GLOBAL
          secretId: "fff750cb-192f-c9ef-148a-05aada3b0ea4"
          usePolicies: false
      - vaultUsernamePasswordCredentialImpl:
          description: "vault-jenkins"
          engineVersion: 1
          id: "vault-jenkins"
          passwordKey: "password"
          path: "secrets/creds/jenkins"
          scope: GLOBAL
          usernameKey: "username"
      - vaultStringCredentialImpl:
          description: "vault-api"
          engineVersion: 1
          id: "vault-api"
          path: "secrets/creds/api-key"
          scope: GLOBAL
          vaultKey: "secret"

jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  disabledAdministrativeMonitors:
  - "jenkins.diagnostics.SecurityIsOffMonitor"
  - "hudson.util.DoubleLaunchChecker"
  labelAtoms:
  - name: "built-in"
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  noUsageStatistics: true
  nodeMonitors:
  - "architecture"
  - "clock"
  - diskSpace:
      freeSpaceThreshold: "1GiB"
      freeSpaceWarningThreshold: "2GiB"
  - "swapSpace"
  - tmpSpace:
      freeSpaceThreshold: "1GiB"
      freeSpaceWarningThreshold: "2GiB"
  - "responseTime"
  numExecutors: 0
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
            - id: jenkins-admin
              password: admin
  slaveAgentPort: 50000
  systemMessage: "CasC enabled!"
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  views:
  - all:
      name: "all"
  viewsTabBar: "standard"
globalCredentialsConfiguration:
  configuration:
    providerFilter: "none"
    typeFilter: "none"
appearance:
  prism:
    theme: PRISM
  themeManager:
    disableUserThemes: false
    theme: "darkSystem"
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  cps:
    hideSandbox: false
  gitHooks:
    allowedOnAgents: false
    allowedOnController: false
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "knownHostsFileVerificationStrategy"
  globalJobDslSecurityConfiguration:
    useScriptSecurity: true
unclassified:
  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"
  enrichedSummaryConfig:
    enrichedSummaryEnabled: false
    httpClientDelayBetweenRetriesInSeconds: 1
    httpClientMaxRetries: 3
    httpClientTimeoutInSeconds: 1
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  globalLibraries:
    libraries:
    - defaultVersion: "master"
      name: "default-lib"
      retriever:
        modernSCM:
          libraryPath: "./"
          scm:
            git:
              id: "4df5e90d-b0a0-4b32-9ffc-992c26149341"
              remote: "https://github.com/hexqueller/IPR.git"
              traits:
              - "gitBranchDiscovery"
  hashicorpVault:
    configuration:
      disableChildPoliciesOverride: false
      engineVersion: 1
      skipSslVerification: true
      timeout: 60
      vaultCredentialId: "vault-jenkins-role"
      vaultUrl: "http://vault:8200"
  injectionConfig:
    allowUntrusted: false
    checkForBuildAgentErrors: false
    enabled: false
    enforceUrl: false
    gradleCaptureTaskInputFiles: true
    injectCcudExtension: false
    injectMavenExtension: false
    mavenCaptureGoalInputFiles: true
  location:
    adminAddress: "адрес еще не настроен <nobody@nowhere>"
    url: "http://localhost:8080/"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  pollSCM:
    pollingThreadCount: 10
  scmGit:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
jobs:
  - script: >
      multibranchPipelineJob('master-git') {
          branchSources {
              git {
                  id = 'master-git'
                  remote('https://github.com/hexqueller/ipr_jenkins.git')
              }
          }
      }